version: "3.8"
services:
  mlflow-server:
    image: mlflow/mlflow
    command:
      mlflow server --host 0.0.0.0 --backend-store-uri sqlite:///mlflow.db
      --default-artifact-root /mlflow/artifacts
    volumes:
      - ./mlflow:/mlflow
    ports:
      - "5000:5000"
  app:
    build: .
    volumes:
      - .:/thesis
    depends_on:
      - mlflow-server
    environment:
      MLFLOW_TRACKING_URI: http://mlflow-server:5000
